#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

PACKAGES="$(go list -mod=vendor ./...)"

echo Running: go vet
go vet ${PACKAGES}

if ! command -v golangci-lint; then
    echo Skipping validation: no golangci-lint available
    exit
else
    echo Running: golangci-lint
    golangci-lint run --skip-files "zz_.*" --skip-files "pkg/agent/grpc.go"
fi

echo Running: go fmt
test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"

echo Running: go mod verify
go mod verify
